name: Hello World Workflow

on:
  pull_request: # PRが作成されたときに実行

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Hello Worldを出力
        run: echo "Hello World!"
